### ISSUE TITLE
Compatibility with react-test-renderer

### ISSUE THREAD

**Issue by sjgreig27** [frankwallis/react-slidedown#10]
Hello, thank you for writing this component! It's been a big help to me so far. The component works perfectly in the production build but I am having a problem with jest tests which use the react-test-renderer. This is maybe not something that you intend to support but thought I would send on details regardless.

# The Problem

## Versions

"react-test-renderer": "^16.6.3"
"jest": "^22.4.2"
"react-slidedown": "^1.3.0"
"react": "^16.4.2"
"antd": "^3.8.1"

## Description

Here is an example component I would like to test using the react-test-renderer.

```javascript

import * as React from 'react';
import {SlideDown} from 'react-slidedown';
import {Icon} from 'antd';

import './InteractiveListCard.css';
import 'react-slidedown/lib/slidedown.css';

export type InteractiveCardTypeProps<T> = {
    header: string,
    style?: any,
    model: T,
    onDrag?: (event: any) => void,
    onDrop?: (event: any) => void,
    onDelete?: (event: any) => void
    onUp?: (model: T) => void
    onDown?: (model: T) => void
    defaultAsCollapsed?: boolean
}

export type InteractiveCardTypeState = {
    collapsed: boolean,
    transitioning: boolean
}

export class InteractiveListCard<T> extends React.Component<InteractiveCardTypeProps<T>, InteractiveCardTypeState> {

    constructor(props: InteractiveCardTypeProps<T>){
        super(props);
        this.state = {
            collapsed: props.defaultAsCollapsed || false,
            transitioning: false
        };
    }

    transition(event: any){
        if(!this.state.transitioning){
            this.setState({transitioning: true});
        }
    }

    completeTransition(event: any){
        if(this.state.transitioning){
            this.setState({transitioning: false, collapsed: !this.state.collapsed});
        }
    }

    onUp(event: any) {
        if(this.props.onUp && this.props.model){
            return this.props.onUp(this.props.model);
        }
    }

    onDown(event: any) {
        if(this.props.onDown && this.props.model){
            return this.props.onDown(this.props.model);
        }
    }

    onDelete(event: any){
        if(this.props.onDelete && this.props.model){
            return this.props.onDelete(this.props.model);
        }
    }

    render(){

        const contentDisplayedClass: string = 'ant-collapse-content ' + (this.state.collapsed ? 'ant-collapse-content-inactive': 'ant-collapse-content-active');

        // Animation logic
        let arrowClasses: string = 'arrow';
        if(this.state.transitioning && this.state.collapsed){
            arrowClasses += ' rotate_clockwise rotated';
        }
        else if(this.state.transitioning && !this.state.collapsed){
            arrowClasses += ' rotate_anticlock';
        }
        else if(!this.state.transitioning && !this.state.collapsed){
            arrowClasses += ' rotated';
        }

        return (
            <div className="ant-collapse" style={this.props.style} onAnimationEnd={this.completeTransition.bind(this)}>
                <div className="ant-collapse-item ant-collapse-item-active">
                    <div className="ant-collapse-header" >
                        <div role="button" tabIndex={0} onClick={this.transition.bind(this)}><i className={arrowClasses} /></div>
                        <div style={{display: 'flex'}}>
                            <div>{this.props.header}</div>
                            <div style={{marginLeft: 'auto', marginRight: 10}}>
                                <Icon type={'up-circle'} onClick={this.onUp.bind(this)} />
                                <Icon type={'down-circle'} style={{marginLeft: 10}} onClick={this.onDown.bind(this)}/>
                                <Icon type={'delete'} style={{marginLeft: 10}} onClick={this.onDelete.bind(this)}/>
                            </div>
                        </div>
                    </div>
                </div>
                <SlideDown closed={this.state.collapsed}>
                    <div className={contentDisplayedClass}>
                        <div className='ant-collapse-content-box'>
                            {this.props.children}
                        </div>
                    </div>
                </SlideDown>
            </div>

        )
    }
}

```

And here is an example test I would like to run to check that my component is being rendered in an identical manner.

```javascript
import * as React from 'react';
import * as Renderer from "react-test-renderer";
import {InteractiveListCard, InteractiveCardTypeProps} from '../InteractiveListCard';
import {DisplayField} from '../../../common/Types'


describe('InteractiveListCard Component Tests', () => {

    type DisplayFieldInteractiveCard = new() => InteractiveListCard<DisplayField>;
    const TestComponent = InteractiveListCard as DisplayFieldInteractiveCard;

    const demoDisplayField: DisplayField = {
        position: 0,
        is_default: true,
        can_filter: true,
        help_text: 'Help me please!',
        field: 'demo_field',
        field_verbose: 'demo_field',
        field_type: 'CharField',
        path: 'example__',
        path_verbose: 'example__',
        name: 'Demonstration Field'
    };

    const testProps: InteractiveCardTypeProps<DisplayField> = {
        header: demoDisplayField.name,
        model: demoDisplayField,
        defaultAsCollapsed: false
    };

    it('Matches the snapshot when collapsed', () => {
        testProps.defaultAsCollapsed = true;
        const tree = Renderer.create(<TestComponent {...testProps}/>).toJSON();
        expect(tree).toMatchSnapshot();
    });

    it('Matches the snapshot when open', () => {
        testProps.defaultAsCollapsed = false;
        const tree = Renderer.create(<TestComponent {...testProps}/>).toJSON();
        expect(tree).toMatchSnapshot();
    });

});
```

When the tests are run, the following stack trace is generated for the 'Matches the snapshot when collapsed' case

```
TypeError: Cannot read property 'classList' of null

    at SlideDownContent.Object.<anonymous>.SlideDownContent.componentDidMount (.../node_modules/react-slidedown/lib/slidedown.js:31:26)
    at commitLifeCycles (.../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8287:22)
    at commitAllLifeCycles (.../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9583:7)
    at HTMLUnknownElement.callCallback (.../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2331:14)
    at invokeEventListeners (.../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
    at HTMLUnknownElementImpl._dispatch (.../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
    at HTMLUnknownElementImpl.dispatchEvent (.../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
    at HTMLUnknownElementImpl.dispatchEvent (.../node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
    at HTMLUnknownElement.dispatchEvent (.../node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
    at Object.invokeGuardedCallbackDev (.../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2381:16)
    at invokeGuardedCallback (.../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2434:31)
    at commitRoot (.../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9779:7)
    at completeRoot (.../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11210:3)
    at performWorkOnRoot (.../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11139:9)
    at performWork (.../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11047:7)
    at performSyncWork (.../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11021:3)
    at requestWork (.../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10890:5)
    at scheduleWork (.../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10700:5)
    at scheduleRootUpdate (.../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11287:3)
    at updateContainerAtExpirationTime (.../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11315:10)
    at updateContainer (.../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11326:10)
    at Object.create (.../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11842:5)
    at Object.<anonymous> (.../src/components/General/__tests__/InteractiveListCard.test.tsx:38:29)
    at Object.asyncFn (.../node_modules/jest-jasmine2/build/jasmine_async.js:82:37)
    at resolve (.../node_modules/jest-jasmine2/build/queue_runner.js:52:12)
    at new Promise (<anonymous>)
    at mapper (.../node_modules/jest-jasmine2/build/queue_runner.js:39:19)
    at promise.then (.../node_modules/jest-jasmine2/build/queue_runner.js:73:82)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

And for the 'Matches the snapshot when open' test case...

```javascript
TypeError: Cannot read property 'classList' of null

    at SlideDownContent.Object.<anonymous>.SlideDownContent.startTransition (.../node_modules/react-slidedown/lib/slidedown.js:72:26)
    at SlideDownContent.Object.<anonymous>.SlideDownContent.componentWillAppear (.../node_modules/react-slidedown/lib/slidedown.js:36:18)
    at TransitionGroup._this.performAppear (.../node_modules/react-transition-group/TransitionGroup.js:58:19)
    at TransitionGroup.componentDidMount (.../node_modules/react-transition-group/TransitionGroup.js:156:14)
    at commitLifeCycles (.../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8287:22)
    at commitAllLifeCycles (.../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9583:7)
    at HTMLUnknownElement.callCallback (.../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2331:14)
    at invokeEventListeners (.../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
    at HTMLUnknownElementImpl._dispatch (.../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
    at HTMLUnknownElementImpl.dispatchEvent (.../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
    at HTMLUnknownElementImpl.dispatchEvent (.../node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
    at HTMLUnknownElement.dispatchEvent (.../node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
    at Object.invokeGuardedCallbackDev (.../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2381:16)
    at invokeGuardedCallback (.../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2434:31)
    at commitRoot (.../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9779:7)
    at completeRoot (.../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11210:3)
    at performWorkOnRoot (.../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11139:9)
    at performWork (.../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11047:7)
    at performSyncWork (.../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11021:3)
    at requestWork (.../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10890:5)
    at scheduleWork (.../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10700:5)
    at scheduleRootUpdate (.../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11287:3)
    at updateContainerAtExpirationTime (.../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11315:10)
    at updateContainer (.../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11326:10)
    at Object.create (.../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11842:5)
    at Object.<anonymous> (.../src/components/General/__tests__/InteractiveListCard.test.tsx:43:29)
    at Object.asyncFn (.../node_modules/jest-jasmine2/build/jasmine_async.js:82:37)
    at resolve (.../node_modules/jest-jasmine2/build/queue_runner.js:52:12)
    at new Promise (<anonymous>)
    at mapper (.../node_modules/jest-jasmine2/build/queue_runner.js:39:19)
    at promise.then (.../node_modules/jest-jasmine2/build/queue_runner.js:73:82)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

# Candidate Solution

Only apply the changes to styles and classes when the element is present.

```javascript

     SlideDownContent.prototype.startTransition = function (prevHeight) {
        var endHeight = '0px';
        if(this.element) {
            if (!this.props.closed) {
                this.element.classList.remove('closed');
                this.element.style.height = 'auto';
                endHeight = getComputedStyle(this.element).height;
            }
            if (parseFloat(endHeight).toFixed(2) !== parseFloat(prevHeight).toFixed(2)) {
                this.element.classList.add('transitioning');
                this.element.style.height = prevHeight;
                this.element.offsetHeight;
                this.element.style.transitionProperty = 'height';
                this.element.style.height = endHeight;
            }
        }
    };

```

```javascript

    SlideDownContent.prototype.componentDidMount = function () {
        if (this.props.closed && this.element)
            this.element.classList.add('closed');
    };

```

This feels like a very hacky fix but generates snapshots which can be used by the react-test-renderer for comparison. If this fix is inappropriate or a better fix can be proposed then please let me know. If any further information is required then I'm happy to expand upon my explanation.

Once again, thank you for the component! It's really appreciated!

**Comment by frankwallis** [comment]
This should now be fixed in 2.4.4
